name: food_delivery
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  flutter_stripe: ^10.1.1
  http: ^1.2.1
  random_string: ^2.3.1
  image_picker: ^1.1.1
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    # Add your assets here if any
      - images/
      - animation/
    # - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    # Uncomment and add more fonts if needed
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
